### PR TITLE
Added Mac and Mc last names to the training file

### PR DESCRIPTION
**Pull request by Richard-West**
PR for Issue #22

### CODE REVIEW

**Comment by fgregg** [comment]
Thanks for this!

We have a pretty simple tokenizer that just splits on spaces. So, we need these to be labeled like

```xml
<Name><GivenName>Matt</GivenName> <Surname>Mc</Surname> <Surname>Gee</Surname></Name>
```

not

```xml
<Name><GivenName>Matt</GivenName> <Surname>Mc Gee</Surname></Name>
```

**Comment by cathydeng** [comment]
you can follow the steps here instead of typing out labeled training data manually: https://github.com/datamade/probablepeople#creatingadding-labeled-training-data-xml-outfile-from-unlabeled-raw-data-csv-infile

**Comment by Richard-West** [comment]
Thanks for the feedback. I'll make the changes and test locally, then issue a new pull request.

**Comment by Richard-West** [comment]
@cathydeng I'm looking at the instructions the create the labeled training data that you provided. It appears to want to take in a CSV file. Are there an examples of what this CSV data needs to look like? The CSV files in the name_data/unlabeled folder of the project don;t appear to have headers so it is not clear how this data would be used to generate the labeled.xml file.

**Comment by cathydeng** [comment]
hey @Richard-West - the csv doesn't need any headers - it can look like
```
"Mr. Brian Mac Kenzie"
"Mr. Mac Isaac"
"Ms. Alice Mac Leod"
"Mr. Mac P Shain"
```

**Comment by Richard-West** [comment]
Thanks @cathydeng . I'm going to close this pull request, and issue another one later today.

**This is an example where test driven development, or in this case test driven *training*, really shines.**

It turns out that only two of my example names are not being handled by the current training file. 

Therefore to keep things tidy in your repository I think it will be best to close this PR and issue a new one after I revert back to your current repository version.

**Pull request closed without merging**
