### PR TITLE
Add Python 3 classifiers to setup.py

### PR DESCRIPTION
**Pull request by nchammas**
Looking at the commit and issue history, plus some quick testing right now, it seems that probablepeople is Python 3-compatible (and intended to be as such). However, setup.py is missing the appropriate classifiers. This PR add those classifiers in.

### CODE REVIEW

**Comment by nchammas** [comment]
On the topic of classifiers, I dunno if the maintainers still see this project as `'Development Status :: 3 - Alpha'`. Given how long it's been out, I assume this project is at least in Beta status, if not production-ready (despite the < 1.0 version tag).

**Comment by jeancochrane** [comment]
Sorry I missed this @nchammas! Mostly agreed. Going off of the [Travis config](https://github.com/datamade/probablepeople/blob/master/.travis.yml#L5-L7), it looks like we only test py2.7 and 3.4. IMO our tags should only list Python versions we test against, mind either adding 3.5 to Travis or updating `setup.py` to reflect the current status?

**Comment by nchammas** [comment]
I can adjust this but just FYI I'm AFK for a while and won't get to this soon.

**Comment by jeancochrane** [comment]
No rush, take your time.

**Comment by nchammas** [comment]
@jeancochrane - I've updated the PR.

**Comment by jeancochrane** [comment]
Thanks again for this @nchammas! Apologies about the long wait.

**Pull request merged**
